# Automatically open PRs to update outdated deps
# See https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  # Enable version updates for cargo
  - package-ecosystem: "cargo"
    # Look for Cargo `.toml` and `.lock` files in the `root` directory
    directory: "/"
    # Check the cargo registry for updates every week
    schedule:
      interval: "weekly"
  # Enable version updates for githubactions
  - package-ecosystem: "github-actions"
    # limit no of pull request dependabot can open
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
